# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# Added manually by Will Landau

branches:
  except:
  - gh-pages

warnings_are_errors: true

r_packages:
  - covr
  - lintr

after_success:
  - Rscript -e 'lintr::lint_package()'

after_failure:
  - find *Rcheck -name '*fail' -print -exec cat '{}' \;
